= La problématique du projet avec Odoo

== Le scénario actuel

- 20 tickets créer pour l'encodage des notes.

- 8 tickets pour la première version de développement, seulement 2 ont été fermés, 1 seul directement liée a l'encodage des notes.

- La quantité de tickets augmente après les réunions avec l'utilisateur, mais pas beaucoup (1 seul ticket après la dernière réunion).

- 4 ressources à temps plein et pas de résultats concrets pour le moment.

== Solution actuelle

=== Odoo

==== Les avantages

- Facile à créer des entités business et les interfaces utilisateur pour maintenir les données quand il y a un écran pour une table ou quand il y a une hierarchie des entités.

- Les services web sont prêts à l'emploi. Aucun d'effort pour les développeurs.

- Plusieurs modules réutilisables et extensibles, peut-être utile pour l'université sur le long terme.

==== Les inconvénients

. Lors de nos développements nous avons remarqué qu'il n'était pas toujours évident de mettre en commun nos codes. Le code qui fonctionne chez un développeur ne fonctionnera pas nécessairement chez son collègue. L'origine du problème c'est peut être le stockage de l'état général de l'application dans la base de données. Énormément d'informations y sont encodées et quand on modifie des identifiants, des colonnes, des noms de vues tout reste stocké en base de données et pollue les données.

. L'utilisation de XML pour la programmation rend difficile d'identifier les causes des problèmes. Les messages d'erreur ne sont pas si clairs que ceux produits par le compilateur Python.

. La documentation couvre seulement les sujets plus basiques. Le forum principal est payant et comme Odoo change chaque année la documentation sur l'internet devient obsolète très rapidement.

. C'est dur de manipuler les données que viennent de tables différentes. On est obligé de passer par la création de vues sql. Si c'est le cas pour tous les écrans sûr mesure, on augmente le couplage avec le modèle. Cela signifie que si un seul champ change dans le modèle plusieurs vues vont casser en même temps. (ex. https://github.com/htmfilho/training-ucl/blob/master/epc/models/activityinfoanalysis.py[activityinfoanalysis.py])

. C'est nécessaire de redémarrer chaque fois que nous changeons quelque chose. C'est également le cas pour l'EPC, mais tous les frameworks modernes ne forcent plus le développeur a redémarrer à chaque changement. Cela signifie que nous allons reporter un problème que est déjà résolu par plusieurs frameworks.

. Une petite erreur dans un module casse l'ensemble du système, car les modules ne sont pas isolés.

. Il supporte une seule base de données: PostgreSQL.

. Il ne peut pas être testée avec Selenium.

. L'impact d'un nouveux "Decret Marcourt" à l'avenir c'est imprévisible.

== Solution alternative

=== Django

==== Les avantages

. Le framework web le plus populaire et puissant sur l'écosystème Python. Largement soutenu par la majorité des plates-formes, les IDEs et les serveurs Web en général.

. Il supporte plusieurs base de données: Oracle, PortgreSQL, MySQL, etc.

. Moins complexe que Odoo. Il suffit de maîtriser Python, les bibliotèques que viennent avec et réutiliser les connaissances existantes de HTML, CSS et JavaScript. Pas besoin d'un langage spécifique de domaine comme l'utilisation de XML dans Odoo.

. Les modifications sont immédiatement répercutées sur le navigateur (sauf les changements dans le modèle). Pas besoin de redémarrer. Corrections en production sans downtime.

. Facilement testable avec Selenium.

==== Les inconvénients

. Le résultat final pour un CRUD (Create, Read, Update and Delete) pour une entité est moins optimale que en Odoo.

. La securité est plus simple que en Odoo. En tout cas, l'ensemble du module de sécurité a été conçu et mis en œuvre pour l'EPC V2 et peut être porté à DJango pour répondre aux besoins du projet.
